const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Date,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Date.Exps.Difference,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Exps.Value
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{WoodTile: 0},
	{Bool: 0},
	{Tween: 0},
	{btnMenu: 0},
	{btnSettings: 0},
	{btnShop: 0},
	{boardCoins: 0},
	{btnPlay: 0},
	{bet: 0},
	{Physics: 0},
	{ball: 0},
	{BetBoard: 0},
	{btnBetAdd: 0},
	{btnBetSubmact: 0},
	{btnHoleActionAdd: 0},
	{btnHoleActionSubmact: 0},
	{HoleActionBoard: 0},
	{HolesPlace: 0},
	{pin: 0},
	{action: 0},
	{num: 0},
	{Hole: 0},
	{board: 0},
	{OutLineHole: 0},
	{Sine: 0},
	{bonus: 0},
	{GameLogo: 0},
	{backgroundLine: 0},
	{LineLoading: 0},
	{OutLineLine: 0},
	{BetNum: 0},
	{HoleActionsNum: 0},
	{HoleActionsNum2: 0},
	{Coins: 0},
	{Type: 0},
	{Price: 0},
	{Pin: 0},
	{BonusFont: 0},
	{Date: 0},
	{GetCoin: 0},
	{boardSettings: 0},
	{btnCloseSettings: 0},
	{OutLineBackgroundSound: 0},
	{SoundBackgroundLine: 0},
	{LineMusic: 0},
	{LineSound: 0},
	{DragDrop: 0},
	{SliderMusic: 0},
	{SliderSound: 0},
	{boardShop: 0},
	{btnCloseShop: 0},
	{btnBallGreen: 0},
	{btnBallPink: 0},
	{btnBallPurple: 0},
	{btnBallRed: 0},
	{LogoShop: 0},
	{Sine2: 0},
	{CoinsLogo: 0},
	{Particles: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Balls: 0},
	{Bet: 0},
	{HoleActions: 0},
	{CurBall: 0},
	{Count: 0},
	{DateBlock: 0},
	{BuyBall: 0}
];

self.InstanceType = {
	WoodTile: class extends self.ITiledBackgroundInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnSettings: class extends self.ISpriteInstance {},
	btnShop: class extends self.ISpriteInstance {},
	boardCoins: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	BetBoard: class extends self.ISpriteInstance {},
	btnBetAdd: class extends self.ISpriteInstance {},
	btnBetSubmact: class extends self.ISpriteInstance {},
	btnHoleActionAdd: class extends self.ISpriteInstance {},
	btnHoleActionSubmact: class extends self.ISpriteInstance {},
	HoleActionBoard: class extends self.ISpriteInstance {},
	HolesPlace: class extends self.ISpriteInstance {},
	pin: class extends self.ISpriteInstance {},
	Hole: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	OutLineHole: class extends self.ISpriteInstance {},
	bonus: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	backgroundLine: class extends self.ISpriteInstance {},
	LineLoading: class extends self.ISpriteInstance {},
	OutLineLine: class extends self.ISpriteInstance {},
	BetNum: class extends self.ISpriteFontInstance {},
	HoleActionsNum: class extends self.ISpriteFontInstance {},
	HoleActionsNum2: class extends self.ISpriteFontInstance {},
	Coins: class extends self.ISpriteFontInstance {},
	Price: class extends self.ISpriteFontInstance {},
	BonusFont: class extends self.ISpriteFontInstance {},
	GetCoin: class extends self.ISpriteFontInstance {},
	boardSettings: class extends self.ISpriteInstance {},
	btnCloseSettings: class extends self.ISpriteInstance {},
	OutLineBackgroundSound: class extends self.ISpriteInstance {},
	SoundBackgroundLine: class extends self.ISpriteInstance {},
	LineMusic: class extends self.ISpriteInstance {},
	LineSound: class extends self.ISpriteInstance {},
	SliderMusic: class extends self.ISpriteInstance {},
	SliderSound: class extends self.ISpriteInstance {},
	boardShop: class extends self.ISpriteInstance {},
	btnCloseShop: class extends self.ISpriteInstance {},
	btnBallGreen: class extends self.ISpriteInstance {},
	btnBallPink: class extends self.ISpriteInstance {},
	btnBallPurple: class extends self.ISpriteInstance {},
	btnBallRed: class extends self.ISpriteInstance {},
	LogoShop: class extends self.ISpriteInstance {},
	CoinsLogo: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Balls: class extends self.IArrayInstance {},
	Date: class extends self.IInstance {}
}